const colors = {
  light: {
    text: "#1A2E1A",
    tint: "#2D7D46",
    background: "#F4F9F4",
    foreground: "#1A2E1A",
    card: "#FFFFFF",
    cardForeground: "#1A2E1A",
    primary: "#2D7D46",
    primaryForeground: "#FFFFFF",
    secondary: "#E8F5E9",
    secondaryForeground: "#1A2E1A",
    muted: "#EEF5EE",
    mutedForeground: "#6B8C6B",
    accent: "#FF8C42",
    accentForeground: "#FFFFFF",
    destructive: "#E53935",
    destructiveForeground: "#FFFFFF",
    border: "#D4E8D4",
    input: "#D4E8D4",
    success: "#43A047",
    successLight: "#E8F5E9",
    gold: "#FFC107",
    surface: "#FFFFFF",
  },
  dark: {
    text: "#E8F5E9",
    tint: "#66BB6A",
    background: "#0E1E0E",
    foreground: "#E8F5E9",
    card: "#162216",
    cardForeground: "#E8F5E9",
    primary: "#66BB6A",
    primaryForeground: "#0E1E0E",
    secondary: "#1E3A1E",
    secondaryForeground: "#E8F5E9",
    muted: "#1A2E1A",
    mutedForeground: "#7BAC7B",
    accent: "#FF8C42",
    accentForeground: "#FFFFFF",
    destructive: "#EF5350",
    destructiveForeground: "#FFFFFF",
    border: "#243C24",
    input: "#243C24",
    success: "#66BB6A",
    successLight: "#1E3A1E",
    gold: "#FFD54F",
    surface: "#162216",
  },
  radius: 16,
};

export default colors;
