name: Build IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Find and Build
        run: |
          # هذا الأمر بيبحث عن مجلد المشروع وين ما كان
          PATH_TO_APP=$(find . -name "package.json" -exec dirname {} \; | head -n 1)
          echo "Found app in: $PATH_TO_APP"
          cd $PATH_TO_APP
          npm install --force
          npx expo export:embed --platform ios --output-dir dist
      - name:
